# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Automatically @generated Cargo.toml for the Rust crate rs_bindings_from_cc_generate_comment.

[package]
name = "rs_bindings_from_cc_generate_comment"
edition.workspace = true

license-file.workspace = true
repository.workspace = true
categories.workspace = true

[lib]
path = "../../../../rs_bindings_from_cc/generate_bindings/generate_comment.rs"

[dependencies]
code_gen_utils = { path = "../../../../cargo/common/code_gen_utils"}
crubit_feature = { path = "../../../../cargo/common/crubit_feature"}
error_report = { path = "../../../../cargo/common/error_report"}
ffi_types = { path = "../../../../cargo/common/ffi_types"}
ir = { path = "../../../../cargo/rs_bindings_from_cc/ir"}
database = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/database/database", package = "rs_bindings_from_cc_database"}
itertools.workspace = true
proc-macro2.workspace = true
quote.workspace = true
